export docs in data.core
fastai/fastai pull request #2761
Opened 2020-09-05 17:30 UTC by KushajveerSingh

Exported docs of TfmdDL and TfmdLists to the library.

2020-09-06 19:05 UTC, jph00 requested changes
Many thanks! Just one change requested

2020-09-06 19:05 UTC, jph00 commented on fastai/data/core.py
> +         decode="From `Pipeline",
Looks like two lines are missing closing backticks here

2020-09-07 17:20 UTC, KushajveerSingh commented on fastai/data/core.py
> +         decode="From `Pipeline",
Done.

2020-09-07 20:17 UTC, KushajveerSingh commented
Done.

2020-09-07 20:22 UTC, merged