fix optimwrapper to work with param_groups (closes #2829)
fastai/fastai pull request #3241
Opened 2021-03-05 07:49 UTC by tmabraham

Currently, `OptimWrapper` does not support `param_groups`, preventing use of model freezing/unfreezing and discriminative learning rate. 

This PR incorporates @muellerzr's [fix](https://muellerzr.github.io/fastai_minima/optimizer.html#Differential-Learning-Rates-and-Groups-with-Pytorch-Optimizers) into `OptimWrapper`. In doing so, the usage of `OptimWrapper` is slightly changed. For example, it changes usage from:
```
def opt_func(params, lr, **kwargs): return OptimWrapper(torch.optim.SGD(params, lr=lr))
```
to
```
def opt_func(params, **kwargs): return OptimWrapper(torch.optim.SGD, params, **kwargs)
```

This PR will also solve issue #2829 as well.

2021-03-05 08:11 UTC, tmabraham commented
I just realized that by switching the arguments of `OptimWrapper`, I can make it even easier to use:
`opt_func = partial(OptimWrapper, opt=torch.optim.SGD)`

I have added this change as a commit, but @jph00 please let me know if you are fine with this. If you think it's too much change to the `OptimWrapper` usage, I will revert back to the previously agreed upon changes...

2021-03-06 01:12 UTC, jph00 requested changes
Looking good! Minor suggestions

2021-03-06 01:12 UTC, jph00 commented on fastai/optimizer.py
> +def convert_params(o:list) -> list:
If this is private, can you prefix it with `_`?

2021-03-06 01:12 UTC, jph00 commented on fastai/optimizer.py
> +        if isinstance(group, dict): return o
Why is this returned rather than added to `splitter`? Can you add a comment explaining what's happening?

2021-03-06 01:12 UTC, jph00 commented on fastai/optimizer.py
> +    def __init__(self, params, opt, hp_map=None, torch_param_groups=True, **kwargs):
```suggestion
    def __init__(self, params, opt, hp_map=None, convert_groups=True, **kwargs):
```

2021-03-06 04:29 UTC, tmabraham commented
@jph00 I made changes based on your suggestions, and also added the doc changes from #3226

2021-03-06 05:48 UTC, jph00 commented
@tmabraham any chance you could look to see why one notebook is timing out in tests in CI?

2021-03-06 07:27 UTC, tmabraham commented
@jph00 fixed! surprised this wasn't an issue before but one of the cells was not marked slow...

2021-03-06 08:45 UTC, jph00 commented
Thank you! :)

2021-03-06 08:45 UTC, merged