Add order to TrackerCallback derived classes
fastai/fastai pull request #3319
Opened 2021-04-13 11:40 UTC by lluissalord

There are some cases where you want to specify that the callback is between the callbacks derived from TrackerCallback. Currently all of them have set `order=60` from its parent, if we make that each callback has its own `order` then it can be specified the desired order.

Proposed order is set according to the current behaviour which is `SaveModelCallback`, `ReduceLROnPlateau` and finally `EarlyStoppingCallback` which is logic to have `EarlyStoppingCallback` as the last one.

2021-04-14 11:29 UTC, Leeeooo19888 approved these changes

2021-04-30 00:20 UTC, jph00 requested changes
Many thanks @lluissalord ! Can you please modify the source notebooks, instead of the .py file directly, and then run make or nbdev_build_lib so that the code is synced with the notebooks?

2021-04-30 11:48 UTC, lluissalord commented
Currently I do not have the fork prepared for contributing and not so much time. If at some point I have time to make the changes I will do as you mentioned. 

However, if someone wants to proceed with this small change then I would appreciate.

2021-04-30 22:55 UTC, jph00 commented
Got it - thanks @lluissalord . I'll close this PR then

2021-04-30 22:55 UTC, closed without merging