Check if normalize exists on `_add_norm`
fastai/fastai pull request #3371
Opened 2021-05-12 10:08 UTC by renato145

Fixes #3370

2021-05-15 21:54 UTC, muellerzr commented
Very nice fix and test! cc: @jph00

2021-05-16 07:52 UTC, jph00 requested changes
Looks great - just a couple of minor suggestions. Please at-mention me when ready to go

2021-05-16 07:52 UTC, jph00 commented on fastai/vision/learner.py
> +    if dls.after_batch.fs.filter(lambda tfm: isinstance(tfm, Normalize)): return
```suggestion
    if dls.after_batch.fs.filter(risinstance(Normalize)):
```

https://fastcore.fast.ai/basics.html#risinstance

2021-05-16 07:52 UTC, jph00 commented on fastai/vision/learner.py
>      dls.add_tfms([Normalize.from_stats(*stats)],'after_batch')
if you change the previous line to `not` then you could move this to the previous line, and get rid of the `return` there

2021-05-16 10:37 UTC, renato145 commented
Ready to go @jph00,  updated with your suggestions.

2021-05-16 13:10 UTC, muellerzr commented
I’ve been made aware of that this only adds Normalize to the train, not the
validation. Can you confirm this Renato? And perhaps maybe we can fix that
here?

On Sun, May 16, 2021 at 6:38 AM Renato Hermoza Aragonés <
***@***.***> wrote:

> Ready to go @jph00 <https://github.com/jph00>, updated with your
> suggestions.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastai/fastai/pull/3371#issuecomment-841798925>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3YCV6EKPBAMEY54CAM763TN6OARANCNFSM44YI2HVA>
> .
>

2021-05-16 15:34 UTC, renato145 commented
@muellerzr I just tried and it was working fine. Can you share and example of that happening?

2021-05-16 16:55 UTC, muellerzr commented
@renato145 thanks for the verification, I believe this may have also been fixed in this latest version (the issue opened up on the forums).

2021-06-16 00:20 UTC, jph00 commented
Many thanks :)

2021-06-16 00:20 UTC, merged