Fix Classification Interpretation
fastai/fastai pull request #3563
Opened 2022-01-25 05:14 UTC by warner-benjamin

Resolves #3562 and adds simple test to make sure `ClassificationInterpretation` doesn't fall through the cracks again.

Implementation does generate the entire datasets' worth of predictions, targets, and decoded predictions, which is required for the confusion matrix. It might be possible to make this more memory efficient, but the labels and predictions for classification problems are not usually that large.

2022-01-25 23:52 UTC, jph00 requested changes
Many thanks - just one request

2022-01-25 23:52 UTC, jph00 commented on nbs/20_interpret.ipynb
> +    "# ! [ -e /content ] && pip install -Uqq fastai  # upgrade fastai on colab"
Could you please uncomment this? It's needed to work on colab

2022-01-25 23:56 UTC, warner-benjamin commented
Done

2022-01-26 00:14 UTC, merged

2022-01-26 00:14 UTC, jph00 commented
Great.

2022-04-24 12:37 UTC, rsomani95 commented
@warner-benjamin With the changes made here, one would be re-running inference on each call of plotting the confusion matrix or fetching the `skm` classification report, right? If so, that could get very cumbersome esp. with larger test sets, and if you wanted to use the stored predictions for anything else.

2022-04-24 19:06 UTC, warner-benjamin commented
@rsomani95 It's on my todo list to add back a cached option

2022-12-13 11:08 UTC, marcocuccarini commented
Hi, i see that the guy that you answer had my same problem but I did't understand the answer. For my example how I can fix the error? I'm sono sorry for the silly question.


`for benchmark in benchmarks:

          training_id, learner = self.create_learner(train_index, valid_index, training_id, 'test' == benchmark)

          print('*'*30)
          print('%s metrics for %s' % (benchmark, training_id))

          metrics = learner.validate()
          
          for (metric, value) in zip(metricsL, metrics):
            results[benchmark][metric].append(value)
            

            interp = DSClassificationInterpretation.from_learner(learner)

          confusion_matrices[benchmark].append(interp.confusion_matrix())
          classification_reports[benchmark].append(interp.classification_report())
`